# Generated by Django 6.0 on 2025-12-24 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
